# Generated by Django 4.1.3 on 2023-02-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='Rating',
        ),
        migrations.AddField(
            model_name='housing',
            name='LandLord',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='landlord',
            name='FullName',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.CreateModel(
            name='LandlordReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Description', models.CharField(max_length=250)),
                ('Landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.landlord')),
            ],
        ),
    ]
