# Generated by Django 4.1.3 on 2023-02-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_landlord_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='LandLord',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='price',
        ),
        migrations.CreateModel(
            name='HousingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
                ('Rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('LandLord', models.CharField(default='none', max_length=200)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.housing')),
            ],
        ),
    ]
