# Generated by Django 4.1.3 on 2023-04-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_housing_description_remove_housing_landlord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordreview',
            name='Landlord',
        ),
        migrations.AddField(
            model_name='housing',
            name='Description',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='housing',
            name='LandLord',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='Rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='landlord',
            name='Description',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='landlord',
            name='Rating',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='HousingReview',
        ),
        migrations.DeleteModel(
            name='LandlordReview',
        ),
    ]
