# Generated by Django 4.2.6 on 2023-10-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_housing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='housing_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
