# Generated by Django 4.2.6 on 2023-10-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_housing_bathrooms_alter_housing_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='Rooms',
        ),
    ]
