# Generated by Django 4.2.6 on 2023-10-17 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_housing_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='Bathrooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
