# Generated by Django 4.2.6 on 2023-10-17 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_housing_bathroom_housing_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='Bathroom',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='Rooms',
        ),
        migrations.AddField(
            model_name='housing',
            name='Bathrooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='housing',
            name='Bedrooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
