# Generated by Django 4.1.3 on 2023-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_landlordreview_landlord_housing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
