# Generated by Django 4.1.7 on 2023-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_housing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='housing',
            name='LandLord',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='housing',
            name='Price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='housing',
            name='Rating',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='Description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='FullName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='Rating',
            field=models.IntegerField(default=''),
        ),
    ]
