# Generated by Django 4.1.7 on 2023-04-11 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_housing_description_alter_housing_landlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Rating',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='Rating',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
