# Generated by Django 4.1.7 on 2023-04-11 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_housing_rating_alter_landlord_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Price',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
