# Generated by Django 4.2.6 on 2023-10-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_housing_housing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='housing_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='housing',
            name='housing_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='housing',
            name='housing_image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='housing',
            name='housing_image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
