# Generated by Django 4.2.6 on 2023-10-17 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_housing_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='Bathroom',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='housing',
            name='Rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
