# Generated by Django 4.1.3 on 2023-04-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_housing_price_alter_landlord_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
