# Generated by Django 4.1.3 on 2023-04-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_housing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
