# Generated by Django 4.2.6 on 2023-10-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_housing_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='Bathrooms',
        ),
    ]
