# Generated by Django 4.2.6 on 2023-10-17 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_housing_bathroom_remove_housing_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='Bathrooms',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='housing',
            name='Bedrooms',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
